### ISSUE TITLE
sorted compiler issue

### ISSUE THREAD

**Issue by GuoFengYung** [mkkellogg/GaussianSplats3D#125]
Hi,
I want to recompile the sorting method.

But I use the command in compile_wasm.sh to run the compilation:
``em++ -std=c++11 sorter.cpp -Os -s WASM=1 -s SIDE_MODULE=2 -o sorter.wasm -s IMPORTED_MEMORY=1 -s USE_PTHREADS=1 -msimd128``

However, the following error will appear on the web side:
``ef845e75-54be-4500-aef9-21fcfe30a44c:153 Uncaught (in promise) LinkError: WebAssembly.instantiate(): Import #0 module="env" function="pthread_self": function import requires a callable
    at ef845e75-54be-4500-aef9-21fcfe30a44c:153:36
(anonymous) @ ef845e75-54be-4500-aef9-21fcfe30a44c:153
Promise.then (async)
self.onmessage @ ef845e75-54be-4500-aef9-21fcfe30a44c:155
``

This error will also occur when using the original sorted.cpp that has not been modified.
I would like to ask what is wrong with my compilation thanks?

My emcc version:emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.53 (ce5114bdd2175c7297583d3c25a53ca95d22f4ce)

**Comment by mkkellogg** [comment]
I'm not really that experienced with using Emscripten or WASM so I don't really know why you're experiencing that error.  For what it's worth, the output of `em++ --version` for me is:
`emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.5 ()`

**Comment by GuoFengYung** [comment]
Hi, After I changed the count to quick sort.
The method to change is as follows:
// Quicksort algorithm - https://en.wikipedia.org/wiki/Quicksort#Hoare_partition_scheme
```
                int iMVPRow3[] = {(int)(modelViewProj[2] * 1000.0), (int)(modelViewProj[6] * 1000.0), (int)(modelViewProj[10] * 1000.0), 1};
                v128_t b = wasm_v128_load(&iMVPRow3[0]);
                for (unsigned int i = sortStart; i < renderCount; i++) {
                    //cal model view depth
                    v128_t a = wasm_v128_load(&intCenters[4 * indexes[i]]);
                    v128_t prod = wasm_i32x4_mul(a, b);
                    wasm_v128_store(&tempOut[0], prod);
                    int distance = tempOut[0] + tempOut[1] + tempOut[2]; //depth

                    // Store the distance at the corresponding index in distances
                    // Store the index i in depthIdx array
                    depthIdx[i] = i;
                    mappedDistances[i] = distance; //depth[i] = depth
                }
            }
        }
    }
    quickSort(mappedDistances, depthIdx, 0, renderCount - 1);
    //save sort result
    for (unsigned int i = sortStart; i < renderCount; i++) {
        indexesOut[i] = depthIdx[i];
    }
```
The projected result will be distorted as follows:
![image](https://github.com/mkkellogg/GaussianSplats3D/assets/43314406/3b0515e1-4f0f-4299-af48-168c0f11d8f8)

How can I fix this error? Thanks

**Comment by mkkellogg** [comment]
My first thought is that my counting sort arranges the splats from furthest to closest, because that's the order in which they need to be rendered, but your `quickSort()` probably sorts in the reverse order?

**Comment by GuoFengYung** [comment]
Thanks! I reversed my fastSort() order and the views are correct.
But there is another problem. When I click on any object with the mouse, this error will appear and the point cannot be tracked.
:
```
Raycaster.js:46 Uncaught TypeError: Cannot read properties of null (reading 'subTrees')
    at Raycaster.intersectSplatMesh (Raycaster.js:46:43)
    at Viewer.checkForFocalPointChange (Viewer.js:341:32)
    at Viewer.onMouseClick (Viewer.js:327:14)
    at Viewer.onMouseUp (Viewer.js:319:22)
```
What does this mean? Thanks!

**Comment by mkkellogg** [comment]
That's actually a bug, right now if you click or touch the screen before the scene has fully loaded and the splat tree has been computed (which is needed for ray-casting) it will give you that error.

**Comment by GuoFengYung** [comment]
Hi, After I changed the count to quick sort to version tag 0.3.3version.
The projected result will be distorted as follows:
![image](https://github.com/mkkellogg/GaussianSplats3D/assets/43314406/2fefc8a0-31f0-42cd-b25a-3845ffc94388)

but when i use tag v0.23 with quick sort(result ok):
![image](https://github.com/mkkellogg/GaussianSplats3D/assets/43314406/bb4d4083-08cc-4db4-8217-e4fbd85b67c4)

How can I debug and fix this error? Thanks

**Comment by mkkellogg** [comment]
I'm not sure exactly what is causing your issues because I don't entirely know what your sort code looks like :) But since `v0.2.3` I made some slight changes to `SortWorker.js` to fix a memory leak issue.

When I run the command
```
git diff v0.2.3..v0.3.3 src/worker/
```
I see

```
diff --git a/src/worker/SortWorker.js b/src/worker/SortWorker.js
index b9f95c3..011c8b4 100644
--- a/src/worker/SortWorker.js
+++ b/src/worker/SortWorker.js
@@ -19,6 +19,7 @@ function sortWorker(self) {
     let centersOffset;
     let modelViewProjOffset;
     let countsZero;
+    let sortedIndexesOut;
 
     let Constants;
 
@@ -59,19 +60,19 @@ function sortWorker(self) {
             'splatRenderCount': splatRenderCount,
             'sortTime': 0
         };
-        const transferBuffers = [];
         if (!useSharedMemory) {
             const sortedIndexes = new Uint32Array(wasmMemory, sortedIndexesOffset, splatRenderCount);
-            const sortedIndexesOut = new Uint32Array(splatRenderCount);
+            if (!sortedIndexesOut || sortedIndexesOut.length < splatRenderCount) {
+                sortedIndexesOut = new Uint32Array(splatRenderCount);
+            }
             sortedIndexesOut.set(sortedIndexes);
-            sortMessage.sortedIndexes = sortedIndexesOut.buffer;
-            transferBuffers.push(sortedIndexesOut.buffer);
+            sortMessage.sortedIndexes = sortedIndexesOut;
         }
         const sortEndTime = performance.now();
 
         sortMessage.sortTime = sortEndTime - sortStartTime;
 
-        self.postMessage(sortMessage, transferBuffers);
+        self.postMessage(sortMessage);
     }
 
     self.onmessage = (e) => {

```

Do any of those changes look like they would have caused a problem for you?

**Comment by GuoFengYung** [comment]
My sort code looks like in sorted.cpp:

      void swap(int *a, int *b) {
          int temp = *a;
          *a = *b;
          *b = temp;
      }

    int partition(int* mappedDistances, int* depthIdx, int low, int high) {
        int pivotIndex = (low + high) / 2; // 使用中位數索引
        int pivot = mappedDistances[pivotIndex];
        int i = low - 1;
        int j = high + 1;

    while (true) {
        do { i++; } while (mappedDistances[i] > pivot);
        do { j--; } while (mappedDistances[j] < pivot);

        if (i >= j) return j;

        // Swap elements
        swap(&mappedDistances[i], &mappedDistances[j]);
        swap(&depthIdx[i], &depthIdx[j]);
         }
     }

      void quickSort(int* mappedDistances, int* depthIdx, int low, int high) {
          if (low < high) {
              int pi = partition(mappedDistances, depthIdx, low, high);
      
              // Recursive calls on smaller subarrays
              quickSort(mappedDistances, depthIdx, low, pi);
              quickSort(mappedDistances, depthIdx, pi + 1, high);
          }
      }

    EXTERN EMSCRIPTEN_KEEPALIVE void sortIndexes(int* indexes, void* centers, void* precomputedDistances,
                                                 int* mappedDistances, unsigned int * frequencies, float* modelViewProj,
                                                 int* indexesOut,  int* transformIndexes, float* transforms,
                                                 unsigned int distanceMapRange, unsigned int sortCount, unsigned int renderCount,
                                                 unsigned int splatCount, bool usePrecomputedDistances, bool useIntegerSort,
                                                 bool dynamicMode, int* depthIdx) {

    int maxDistance = -2147483640;
    int minDistance = 2147483640;

    float fMVPTRow3[4];
    unsigned int sortStart = renderCount - sortCount;
    // Assuming you have declared arrays for distances and indexes

    if (useIntegerSort) {
        int* intCenters = (int*)centers;
        if (usePrecomputedDistances) {
            int* intPrecomputedDistances = (int*)precomputedDistances;
            for (unsigned int i = sortStart; i < renderCount; i++) {
                int distance = intPrecomputedDistances[indexes[i]];
                // Store the distance at the corresponding index in distances
                // Store the index i in depthIdx array
                indexesOut[i] = i;
                mappedDistances[i] = distance; //depth[i] = depth
                if (distance > maxDistance) maxDistance = distance;
                if (distance < minDistance) minDistance = distance;
            }....
      quickSort(mappedDistances, indexesOut, 0, renderCount - 1);
    }

And the restore of sortworker.js, the results don't seem to reflect my results

Thanks your reply

**Comment by mkkellogg** [comment]
It seems like you have omitted some code above,  right where you have `....` I get compile errors when I try to build it.

**Comment by GuoFengYung** [comment]
Hi my all code is here:
assigning values to the arrays indexesOut and mappedDistances at index i within the loop.
And  quickSort to sort two lists together: mappedDistances and indexesOut.
```
#include <emscripten/emscripten.h>
#include <iostream>
#include <wasm_simd128.h>

#ifdef __cplusplus
#define EXTERN extern "C"
#else
#define EXTERN
#endif

void swap(int *a, int *b) {
    int temp = *a;
    *a = *b;
    *b = temp;
}

int partition(int* mappedDistances, int* depthIdx, int low, int high) {
    int pivotIndex = low + (high - low) / 2;
    int pivot = mappedDistances[pivotIndex];
    int i = low - 1;
    int j = high + 1;

    while (true) {
        do { i++; } while (mappedDistances[i] < pivot);
        do { j--; } while (mappedDistances[j] > pivot);

        if (i >= j) return j;

        // Swap elements
        swap(&mappedDistances[i], &mappedDistances[j]);
        swap(&depthIdx[i], &depthIdx[j]);
    }
}

void quickSort(int* mappedDistances, int* depthIdx, int low, int high) {
    if (low < high) {
        int pi = partition(mappedDistances, depthIdx, low, high);

        // Recursive calls on smaller subarrays
        quickSort(mappedDistances, depthIdx, low, pi);
        quickSort(mappedDistances, depthIdx, pi + 1, high);
    }
}


#define computeMatMul4x4ThirdRow(a, b, out) \
    out[0] = a[2] * b[0] +  a[6] * b[1] + a[10] * b[2] + a[14] * b[3]; \
    out[1] = a[2] * b[4] +  a[6] * b[5] + a[10] * b[6] + a[14] * b[7]; \
    out[2] = a[2] * b[8] +  a[6] * b[9] + a[10] * b[10] + a[14] * b[11]; \
    out[3] = a[2] * b[12] +  a[6] * b[13] + a[10] * b[14] + a[14] * b[15];

EXTERN EMSCRIPTEN_KEEPALIVE void sortIndexes(unsigned int* indexes, void* centers, void* precomputedDistances, 
                                             int* mappedDistances, unsigned int * frequencies, float* modelViewProj,
                                             int* indexesOut,  unsigned int* transformIndexes, float* transforms,
                                             unsigned int distanceMapRange, unsigned int sortCount, unsigned int renderCount,
                                             unsigned int splatCount, bool usePrecomputedDistances, bool useIntegerSort,
                                             bool dynamicMode) {

    int maxDistance = -2147483640;
    int minDistance = 2147483640;

    float fMVPTRow3[4]; 
    unsigned int sortStart = renderCount - sortCount;
    if (useIntegerSort) {
        int* intCenters = (int*)centers;
        if (usePrecomputedDistances) {
            int* intPrecomputedDistances = (int*)precomputedDistances;
            for (unsigned int i = sortStart; i < renderCount; i++) {
                int distance = intPrecomputedDistances[indexes[i]];
                indexesOut[i] = i;
                mappedDistances[i] = distance;
                if (distance > maxDistance) maxDistance = distance;
                if (distance < minDistance) minDistance = distance;
            }
        }
        else {
            int tempOut[4];
            if (dynamicMode) {
                int lastTransformIndex = -1;
                v128_t b;
                for (unsigned int i = sortStart; i < renderCount; i++) {
                    unsigned int realIndex = indexes[i];
                    unsigned int transformIndex = transformIndexes[realIndex];
                    if ((int)transformIndex != lastTransformIndex) {
                        float* transform = &transforms[transformIndex * 16];
                        computeMatMul4x4ThirdRow(modelViewProj, transform, fMVPTRow3);
                        int iMVPTRow3[] = {(int)(fMVPTRow3[0] * 1000.0), (int)(fMVPTRow3[1] * 1000.0),
                                           (int)(fMVPTRow3[2] * 1000.0), (int)(fMVPTRow3[3] * 1000.0)};
                        b = wasm_v128_load(&iMVPTRow3[0]);
                        lastTransformIndex = (int)transformIndex;
                    }
                    v128_t a = wasm_v128_load(&intCenters[4 * realIndex]);
                    v128_t prod = wasm_i32x4_mul(a, b);
                    wasm_v128_store(&tempOut[0], prod);
                    int distance = tempOut[0] + tempOut[1] + tempOut[2] + tempOut[3];
                    mappedDistances[i] = distance;
                    if (distance > maxDistance) maxDistance = distance;
                    if (distance < minDistance) minDistance = distance;
                }
            }
            else {
                int iMVPRow3[] = {(int)(modelViewProj[2] * 1000.0), (int)(modelViewProj[6] * 1000.0), (int)(modelViewProj[10] * 1000.0), 1};
                v128_t b = wasm_v128_load(&iMVPRow3[0]);
                for (unsigned int i = sortStart; i < renderCount; i++) {
                    v128_t a = wasm_v128_load(&intCenters[4 * indexes[i]]);
                    v128_t prod = wasm_i32x4_mul(a, b);
                    wasm_v128_store(&tempOut[0], prod);
                    int distance = tempOut[0] + tempOut[1] + tempOut[2];
                    indexesOut[i] = i;
                    mappedDistances[i] = distance;
//                    if (distance > maxDistance) maxDistance = distance;
//                    if (distance < minDistance) minDistance = distance;
                }
            }
        }
    } else {
        float* floatCenters = (float*)centers;
        if (usePrecomputedDistances) {
            float* floatPrecomputedDistances = (float*)precomputedDistances;
            for (unsigned int i = sortStart; i < renderCount; i++) {
                int distance = (int)(floatPrecomputedDistances[indexes[i]] * 4096.0);
                mappedDistances[i] = distance;
                if (distance > maxDistance) maxDistance = distance;
                if (distance < minDistance) minDistance = distance;
            }
        } else {
            float* fMVP = (float*)modelViewProj;
            float* floatTransforms = (float *)transforms;

            // TODO: For some reason, the SIMD approach with floats seems slower, need to investigate further...
            /* 
            float tempOut[4];
            float tempViewProj[] = {fMVP[2], fMVP[6], fMVP[10], 1.0};
            v128_t b = wasm_v128_load(&tempViewProj[0]);
            for (unsigned int i = sortStart; i < renderCount; i++) {
                v128_t a = wasm_v128_load(&floatCenters[4 * indexes[i]]);
                v128_t prod = wasm_f32x4_mul(a, b);
                wasm_v128_store(&tempOut[0], prod);
                int distance = (int)((tempOut[0] + tempOut[1] + tempOut[2]) * 4096.0);
                mappedDistances[i] = distance;
                if (distance > maxDistance) maxDistance = distance;
                if (distance < minDistance) minDistance = distance;
            }
            */

            if (dynamicMode) {
                int lastTransformIndex = -1;
                for (unsigned int i = sortStart; i < renderCount; i++) {
                    unsigned int realIndex = indexes[i];
                    unsigned int indexOffset = 4 * realIndex;
                    unsigned int transformIndex = transformIndexes[realIndex];
                    if ((int)transformIndex != lastTransformIndex) {
                        float* transform = &transforms[transformIndex * 16];
                        computeMatMul4x4ThirdRow(modelViewProj, transform, fMVPTRow3);
                        lastTransformIndex = (int)transformIndex;
                    }
                    int distance =
                        (int)((fMVPTRow3[0] * floatCenters[indexOffset] +
                               fMVPTRow3[1] * floatCenters[indexOffset + 1] +
                               fMVPTRow3[2] * floatCenters[indexOffset + 2] +
                               fMVPTRow3[3] * floatCenters[indexOffset + 3]) * 4096.0);
                    mappedDistances[i] = distance;
                    if (distance > maxDistance) maxDistance = distance;
                    if (distance < minDistance) minDistance = distance;
                }
            } else {
                for (unsigned int i = sortStart; i < renderCount; i++) {
                    unsigned int indexOffset = 4 * (unsigned int)indexes[i];
                    int distance =
                        (int)((fMVP[2] * floatCenters[indexOffset] +
                               fMVP[6] * floatCenters[indexOffset + 1] +
                               fMVP[10] * floatCenters[indexOffset + 2]) * 4096.0);
                    indexesOut[i] = i;
                    mappedDistances[i] = distance;
                    if (distance > maxDistance) maxDistance = distance;
                    if (distance < minDistance) minDistance = distance;
                }
            }
        }
    }


    quickSort(mappedDistances, indexesOut, 0, renderCount - 1);

//    for (unsigned int gap = renderCount / 2; gap > 0; gap /= 2) {
//        for (unsigned int i = gap; i < renderCount; i++) {
//            float tempDistance = mappedDistances[i];
//            unsigned int tempIndex = indexes[i];
//            unsigned int j;
//            for (j = i; j >= gap && mappedDistances[j - gap] > tempDistance; j -= gap) {
//                mappedDistances[j] = mappedDistances[j - gap];
//                indexes[j] = indexes[j - gap];
//            }
//            mappedDistances[j] = tempDistance;
//            indexes[j] = tempIndex;
//        }
//    }
//
//    float distancesRange = (float)maxDistance - (float)minDistance;
//    float rangeMap = (float)(distanceMapRange - 1) / distancesRange;
//
//    for (unsigned int i = sortStart; i < renderCount; i++) {
//        unsigned int frequenciesIndex = (int)((float)(mappedDistances[i] - minDistance) * rangeMap);
//        mappedDistances[i] = frequenciesIndex;
//        frequencies[frequenciesIndex] = frequencies[frequenciesIndex] + 1;
//    }
//
//    unsigned int cumulativeFreq = frequencies[0];
//    for (unsigned int i = 1; i < distanceMapRange; i++) {
//        unsigned int freq = frequencies[i];
//        cumulativeFreq += freq;
//        frequencies[i] = cumulativeFreq;
//    }
//
//    for (int i = (int)sortStart - 1; i >= 0; i--) {
//        indexesOut[i] = indexes[i];
//    }
//
//    for (int i = (int)renderCount - 1; i >= (int)sortStart; i--) {
//        unsigned int frequenciesIndex = mappedDistances[i];
//        unsigned int freq = frequencies[frequenciesIndex];
//        indexesOut[renderCount - freq] = indexes[i];
//        frequencies[frequenciesIndex] = freq - 1;
//    }
}
```

**Comment by mkkellogg** [comment]
So I modified a couple of things and it seems like it works on my end. First, I updated the `partition()` function to reverse the order:

```
int partition(int* mappedDistances, int* depthIdx, int low, int high) {
    int pivotIndex = low + (high - low) / 2;
    int pivot = mappedDistances[pivotIndex];
    int i = low;
    int j = high;

    while (true) {
        do { i++; } while (mappedDistances[i] > pivot && i <= j);
        do { j--; } while (mappedDistances[j] < pivot && i <= j);

        if (i >= j) return j;

        // Swap elements
        swap(&mappedDistances[i], &mappedDistances[j]);
        swap(&depthIdx[i], &depthIdx[j]);
    }
}
```

Then I changed every instance of 

```
indexesOut[i] = i;
```
to
```
indexesOut[i] = indexes[i];
```

**Comment by GuoFengYung** [comment]
It works !!
Thank you so much for helping out
